<?php

namespace SeoBundle\Repository;

/**
 * CampingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampingRepository extends \Doctrine\ORM\EntityRepository
{
	
}
