<?php

namespace SeoBundle\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{

	public function findSite($region, $departement, $ville)
	{

	 return $this->createQueryBuilder('s')
		->where('(s.region = 139 ) OR
			(s.region = :region_id AND s.departement = :departement_id AND s.ville IS NULL) OR
			s.region = :region_id AND s.departement = :departement_id AND s.ville = :ville_id') 
		
	    ->setParameter('region_id', $region)
	    ->setParameter('departement_id', $departement)
	    ->setParameter('ville_id', $ville)
	   	->getQuery()
	    ->getResult()
	  ;
	}
}
