<?php

namespace SeoBundle\Repository;

/**
 * TopicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicalRepository extends \Doctrine\ORM\EntityRepository
{
}
