<?php

namespace SeoBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findVille($departement)    {

	return $this->createQueryBuilder('v')      
            ->where('v.departemnt= :departement')
            ->setParameter('departement', $departement)
 			->getQuery()
          	->getArrayResult();
	}
}
