seo_statut:
    resource: "@SeoBundle/Controller/StatutController.php"
    type:     annotation

seo_topical:
    resource: "@SeoBundle/Controller/TopicalController.php"
    type:     annotation

seo_type:
    resource: "@SeoBundle/Controller/TypeController.php"
    type:     annotation

seo_langue:
    resource: "@SeoBundle/Controller/LangueController.php"
    type:     annotation

seo_departement:
    resource: "@SeoBundle/Controller/DepartementController.php"
    type:     annotation

seo_region:
    resource: "@SeoBundle/Controller/RegionController.php"
    type:     annotation

seo_ville:
    resource: "@SeoBundle/Controller/VilleController.php"
    type:     annotation

seo_site:
    resource: "@SeoBundle/Controller/SiteController.php"
    type:     annotation

seo_site:
    resource: "@SeoBundle/Controller/siteController.php"
    type:     annotation

seo_camping:
    resource: "@SeoBundle/Controller/CampingController.php"
    type:     annotation

seo_site:
    resource: "@SeoBundle/Controller/SiteController.php"
    type:     annotation

user_role:
    resource: "@UserBundle/Controller/RoleController.php"
    type:     annotation

seo:
    resource: "@SeoBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login: 
  path: /login
  defaults:
    _controller: UserBundle:Security:login

login_check:
  path: /login_check

logout:
  path: /logout

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error


    