# Documentation correspondant à la mise en place de la sécurité
# http://symfony.com/doc/current/security/entity_provider.html
security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN,ROLE_USER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: UserBundle:User
                
    


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  

        # neutralise le firewall secured_area et permet à un anonyme d'accéder au login
        login: 
            pattern: ^/login$
            anonymous: true

        # firewall pour l'ensemble du site
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /login

       