# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # neutralise le firewall secured_area et permet à un anonyme d'accéder au login
        secured_login: 
            pattern: ^/login$
            anonymous: true

        # firewall pour l'ensemble du site
        secured_area:
            pattern: ^/
            anonymous: false
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /index
            