# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: [ROLE_ADMIN]
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: UserBundle:User

    firewalls:
        firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path : /login
                check_path : /login
                default_target_path: /index
            logout:
                path: /logout
                target: /index

        # disables authentication for assets and the profiler, adapt it according to your needs
        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        access_control:
        - { path: ^/admin, roles : ROLE_ADMIN }
        #- { path: ^/efconnect, roles: ROLE_ADMIN }
        #- { path: ^/elfinder, roles: ROLE_ADMIN }

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
            
